export const FETCH_SELECT_CANDIDATE = 'FETCH_SELECT_CANDIDATE'
export const FETCH_SELECT_CANDIDATE_SUCCESS = 'FETCH_SELECT_CANDIDATE_SUCCESS'
export const FETCH_SELECT_CANDIDATE_FAIL = 'FETCH_SELECT_CANDIDATE_FAIL'