export const FETCH_REJECT_CANDIDATE = 'FETCH_REJECT_CANDIDATE'
export const FETCH_REJECT_CANDIDATE_SUCCESS = 'FETCH_REJECT_CANDIDATE_SUCCESS'
export const FETCH_REJECT_CANDIDATE_FAIL = 'FETCH_REJECT_CANDIDATE_FAIL'